   OBJ = 

   LIBRARY = libdimqm.a

   LIB_DEFINES = -DDBLEPREC_RYS

   LIB_INCLUDES = -I../../nwdft/include \
                  -I../../ddscf \
                  -I../../util \
                  -I../../nwdft/grid \
                  -I../../NWints/hondo

include ../../config/makefile.h
include ../../config/makelib.h

#erf.o : erf.f90
#	$(FC) -c -fpp erf.f90
#FDEBUG += -O0
